# Generated by Django 5.0.4 on 2024-06-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDAVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_base64', models.TextField()),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadedfile')),
            ],
        ),
    ]
