# Generated by Django 5.0.4 on 2024-06-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
