# Generated by Django 5.0.4 on 2024-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('Water Quality Site', 'Water Quality Site'), ('Hydrology Station', 'Hydrology Station'), ('Groundwater Station', 'Groundwater Station')], max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('srid', models.IntegerField()),
            ],
        ),
    ]
